name: build-and-test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DTWOSUM_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build --output-on-failure --build-config Release
